#################UNINSTALL BLOATWARE APPS############################
Get-AppxPackage -allusers *3dbuilder* | Remove-AppxPackage 
Get-AppxPackage -allusers *Mail* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsalarms* | Remove-AppxPackage
Get-AppxPackage -allusers *windowscalculator* | Remove-AppxPackage
Get-AppxPackage -allusers *windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage -allusers *windowscamera* | Remove-AppxPackage
Get-AppxPackage -allusers *officehub* | Remove-AppxPackage
Get-AppxPackage -allusers *skypeapp* | Remove-AppxPackage
Get-AppxPackage -allusers *getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers *zunemusic* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsmaps* | Remove-AppxPackage
Get-AppxPackage -allusers *solitairecollection* | Remove-AppxPackage
Get-AppxPackage -allusers *bingfinance* | Remove-AppxPackage
Get-AppxPackage -allusers *zunevideo* | Remove-AppxPackage
Get-AppxPackage -allusers *bingnews* | Remove-AppxPackage
Get-AppxPackage -allusers *onenote* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsphone* | Remove-AppxPackage
Get-AppxPackage -allusers *photos* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsstore* | Remove-AppxPackage
Get-AppxPackage -allusers *bingsports* | Remove-AppxPackage
Get-AppxPackage -allusers *soundrecorder* | Remove-AppxPackage
Get-AppxPackage -allusers *bingweather* | Remove-AppxPackage
Get-AppxPackage -allusers *Microsoft.XboxGameOverlay_8wekyb3d8bbwe* | Remove-AppxPackage
Get-AppxPackage -allusers *candycrushsodasaga* | Remove-AppxPackage
Get-AppxPackage -allusers *paint3d* | Remove-AppxPackage
Get-AppxPackage -allusers *hiddenCity* | Remove-AppxPackage
Get-AppxPackage -allusers *hiddenCity* | Remove-AppxPackage
Get-AppxPackage -allusers *Myoffice* | Remove-AppxPackage
Get-AppxPackage -allusers *microsoftsolitairecollection* | Remove-AppxPackage
Get-AppxPackage -allusers *mobileplans* | Remove-AppxPackage
Get-AppxPackage -allusers *mail* | Remove-AppxPackage
Get-AppxPackage -allusers *skype* | Remove-AppxPackage
Get-AppxPackage -allusers *todo* | Remove-AppxPackage
Get-AppxPackage -allusers *calendar* | Remove-AppxPackage
Get-AppxPackage -allusers *microsoftstore* | Remove-AppxPackage
Get-AppxPackage -allusers *whiteboard* | Remove-AppxPackage
Get-AppxPackage -allusers *maps* | Remove-AppxPackage
Get-AppxPackage -allusers *calculator* | Remove-AppxPackage
Get-AppxPackage -allusers *Getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers *Messaging* | Remove-AppxPackage
Get-AppxPackage -allusers *Microsoft3DViewer* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftOfficeHub* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftSolitaireCollection* | Remove-AppxPackage
Get-AppxPackage -allusers *MSPaint* | Remove-AppxPackage
Get-AppxPackage -allusers *OneNote* | Remove-AppxPackage
Get-AppxPackage -allusers *OneConnect* | Remove-AppxPackage
Get-AppxPackage -allusers *Microsoft.People* | Remove-AppxPackage
Get-AppxPackage -allusers *Print3D* | Remove-AppxPackage
Get-AppxPackage -allusers *SkypeApp* | Remove-AppxPackage
Get-AppxPackage -allusers *Wallet* | Remove-AppxPackage
Get-AppxPackage -allusers *windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage -allusers *ZuneMusic* | Remove-AppxPackage
Get-AppxPackage -allusers *ZuneVideo* | Remove-AppxPackage
Get-AppxPackage -allusers *BingNews* | Remove-AppxPackage
Get-AppxPackage -allusers *Duolingo* | Remove-AppxPackage
Get-AppxPackage -allusers *Sway* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftPowerBIForWindows* | Remove-AppxPackage
Get-AppxPackage -allusers *PandoraMediaInc* | Remove-AppxPackage
Get-AppxPackage -allusers *RemoteDesktop* | Remove-AppxPackage
Get-AppxPackage -allusers *NetworkSpeedTest* | Remove-AppxPackage
Get-AppxPackage -allusers *AdobePhotoshopExpress* | Remove-AppxPackage
Get-AppxPackage -allusers *EclipseManager* | Remove-AppxPackage
Get-AppxPackage -allusers *ActiproSoftwareLLC* | Remove-AppxPackage
Get-AppxPackage -allusers *Xbox* | Remove-AppxPackage
Get-AppxPackage -allusers *Appconnector* | Remove-AppxPackage
Get-AppxPackage -allusers *BingFinance* | Remove-AppxPackage
Get-AppxPackage -allusers *BingNews* | Remove-AppxPackage
Get-AppxPackage -allusers *CommsPhone* | Remove-AppxPackage
Get-AppxPackage -allusers *BingWeather* | Remove-AppxPackage
Get-AppxPackage -allusers *ConnectivityStore* | Remove-AppxPackage
Get-AppxPackage -allusers *Getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers *Messaging* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftOfficeHub* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftSolitaireCollection* | Remove-AppxPackage
Get-AppxPackage -allusers *OneNote* | Remove-AppxPackage
Get-AppxPackage -allusers *Sway* | Remove-AppxPackage
Get-AppxPackage -allusers *People* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsAlarms* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsCamera** | Remove-AppxPackage
Get-AppxPackage -allusers *windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsMaps* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsPhone* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsSoundRecorder* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsStore* | Remove-AppxPackage
Get-AppxPackage -allusers *Minecraft* | Remove-AppxPackage
Get-AppxPackage -allusers *CandyCrushSaga* | Remove-AppxPackage
Get-AppxPackage -allusers *RoyalRevolt2* | Remove-AppxPackage
Get-AppxPackage -allusers *ZuneMusic* | Remove-AppxPackage
Get-AppxPackage -allusers *king.com.cancrushsaga* | Remove-AppxPackage
Get-AppxPackage -allusers *HiddenCityMysteryofShadow* | Remove-AppxPackage
Get-AppxPackage -allusers *CandyCrushSodaSaga* | Remove-AppxPackage
Get-AppxPackage -allusers *DrawBoardPDF* | Remove-AppxPackage
Get-AppxPackage -allusers *office* | Remove-AppxPackage
Get-AppxPackage -allusers *Dolby* | Remove-AppxPackage
Get-AppxPackage -allusers *MicrosoftStore* | Remove-AppxPackage